[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask-cors>=5.0.1",
    "flask>=3.1.0",
    "flask-jwt-extended>=4.7.1",
    "openai>=1.72.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
